swagger: "2.0"
info:
  description: "This is description."
  version: "1.0.0"
  title: "Go learning APIs"
  # termsOfService: "http://swagger.io/terms/"
  contact:
    email: "liuqi17@xiaomi.com"
  # license:
  #   name: "Apache 2.0"
  #   url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8001"
basePath: "/api"
tags:
- name: "user"
  description: "User APIs"
- name: "file"
  description: "File APIs"
schemes:
# - "https"
- "http"
paths:
  /user/all:
    get:
      tags:
      - "user"
      summary: ""
      description: ""
      operationId: "getAllUser"
      produces:
      - "application/json"
      responses:
        200:
          description: ""
          shecma:
            type: "array"
  /user/login:
    post:
      tags:
      - user
      summary:
      description:
      operationId: loginValidate
      produces:
      - application/json
      parameters:
      - name: username
        in: formData
      - name: password
        in: formData
  /user:
    get:
      tags:
      - "user"
      summary: ""
      description: ""
      operationId: "getUserByID"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
      responses:
        200:
          description: ""
          shecma:
            type: "object"
    post:
      tags:
      - "user"
      summary: ""
      description: ""
      operationId: "postUser"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "formData"
      - name: "password"
        in: "formData"
    put:
      tags:
      - "user"
      summary: ""
      description: ""
      operationId: "putUser"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
      - name: "username"
        in: "formData"
      - name: "password"
        in: "formData"
    delete:
      tags:
      - "user"
      summary: ""
      description: ""
      operationId: "deleteUser"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
  /upload/file:
    post:
      tags:
      - file
      consumes:
      - multipart/form-data
      parameters:
      - name: userId
        in: query
      - name: file
        in: formData
        type: file
        allowMultiple: True
  /file/uploadfiles:
    post:
      tags:
      - file
      consumes:
      - multipart/form-data
      parameters:
      - name: files
        in: formData
        description: Upload multiple files
        required: true
        type: array
        items:
          type: file
        collectionFormat: multi